#!/bin/sh
sxhkd &
dunst &
feh --bg-scale /home/ma/.config/wall.png &
ibus-daemon & 
wechat &
firefox &
redshift -P -O 4200 &
sudo bash /home/ma.local/clash_terminal/start.sh -u https://huahe.link/link/ug1nhgZZ0d7Wpzua?clash=2

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        2
bspc config window_gap          2
bspc config focused_border_color "#b5ada5"
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true




#windows rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Clash-verge desktop='^7'
bspc rule -a wechat desktop='^5'
bspc rule -a WeCom state=floating
bspc rule -a Eog state=floating  rectangle=800x600+1200+50
bspc rule -a mplayer2 state=floating
bspc rule -a R_x11 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



