#!/bin/sh
sxhkd &
bash /home/ma/.config/polybar/launch.sh &
feh --bg-scale /home/ma/.config/wall.png &
/home/ma/.config/clash_verge.AppImage &
picom &
dunst &


bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        2
bspc config window_gap          3
bspc config focused_border_color "#b5ada5"

bspc config borderless_monocle   true
bspc config gapless_monocle      true




#windows rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Clash-verge desktop='^7'
bspc rule -a wechat desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



