remote_id = ''
kb_layout_type = ''
size = [
    0,
    0,
    0,
    0,
]
fav = []

[options]
theme = 'dark'

[ui_flutter]
peer-sorting = 'Remote ID'
wm_Main = '{"width":800.0,"height":600.0,"offsetWidth":1343.0,"offsetHeight":292.0,"isMaximized":false,"isFullscreen":false}'
